### ISSUE TITLE
Question: is there an equivalent for Angular?

### ISSUE THREAD

**Issue by rudolfolah** [GoogleChromeLabs/react-adaptive-hooks#15]
Curious to know if there's an Angular equivalent (or if that's already part of Angular).

Cool project, and thanks!

**Comment by addyosmani** [comment]
Thanks! There's some related thinking in https://bit.ly/adaptive-angular. I'm unaware of a collection of Angular utilities similar to the ones here, but I've reached out to the Angular team about collaborating on one. If something comes together, I'll be sure to link up in a related projects section.
