### ISSUE TITLE
Yarn or NPM?

### ISSUE THREAD

**Issue by mobily** [GoogleChromeLabs/react-adaptive-hooks#16]
@addyosmani I have spotted your Travis configuration is using Yarn, and there's no `yarn.lock` in the repo (there's `package-lock.json` file instead). I don't know whether it's done intentionally or it's just a simple mistake :) In order to get consistent installs across machines, it would be good to pick one of them.

WDYT?

**Comment by addyosmani** [comment]
Thank you for catching this, @mobily. This was an oversight after dropping our yarn lock from the repo and I should have switched over to npm for the Travis configuration too.  Happy to accept a PR to update otherwise this should be quick to update later in the day.

**Comment by mobily** [comment]
@addyosmani switched to `npm` here https://github.com/GoogleChromeLabs/react-adaptive-hooks/pull/17
