### ISSUE TITLE
Add hook for Media Capabilities API

### ISSUE THREAD

**Issue by wingleung** [GoogleChromeLabs/react-adaptive-hooks#25]
_Moved from https://github.com/GoogleChromeLabs/adaptive-loading/pull/60 and https://github.com/GoogleChromeLabs/adaptive-loading/issues/59_

The Media Capabilities API allows websites to get more information about the decoding abilities of the device/system/browser. This enables web developers to make optimal decisions when selecting media streams for the user.

**Comment by addyosmani** [comment]
Thanks for moving this over, @wingleung. Are you interested in working on a fresh PR to add a utility for the Media Capabilities API?

**Comment by wingleung** [comment]
Off course! I'll create a new one
