### ISSUE TITLE
[improvement] In useSaveData hook, instead of useState, useRef can be used

### ISSUE THREAD

**Issue by itaditya** [GoogleChromeLabs/react-adaptive-hooks#4]
useRef is much more suitable than useState when you just want some value to persist across renders. I can make a PR for that change.

**Comment by itaditya** [comment]
Saw PR https://github.com/GoogleChromeLabs/react-adaptive-hooks/pull/1 I guess that would be even better.

**Comment by addyosmani** [comment]
Thanks for the suggestion, @itaditya. We've just landed https://github.com/GoogleChromeLabs/react-adaptive-hooks/pull/1 and hopefully that's a sufficient solution.
