### ISSUE TITLE
mjs file extension breaking CRA

### ISSUE THREAD

**Issue by stramel** [GoogleChromeLabs/react-adaptive-hooks#40]
After the build scripts update, it is breaking CRA apps.

```
Failed to compile.

./node_modules/react-adaptive-hooks/dist/index.mjs
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)
```

CRA doesn't support `.mjs` files and requires a good amount of effort just to use that. From my understanding there is no reason that `.mjs` extension is needed to indicate a ESM file.

Related issues:
 - https://github.com/facebook/create-react-app/issues/4317

@midudev and @addyosmani

**Comment by midudev** [comment]
Thanks for reporting. I've created a PR to fix this as, anyway, the `.mjs` extension is meant to go away (was mean for Node but now it's not longer necessary).

**Comment by addyosmani** [comment]
Thank you for working on a PR pretty quickly to address this, @midudev. I'll review shortly. Appreciate you flagging the CRA breakage, @stramel!

**Comment by midudev** [comment]
A pleasure @addyosmani. Sorry for adding the bug! 🙇
