### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by eltonjothi** [GoogleChromeLabs/react-adaptive-hooks#47]
i am trying to implement the react adaptive hooks on my project but i get the following error.
<img width="1059" alt="Screenshot 2020-01-28 at 5 47 49 PM" src="https://user-images.githubusercontent.com/12094648/73252908-7a6dd500-41f6-11ea-9685-72396ed3730c.png">

i am using Next.js
my test page code is as follows
```
import React from 'react';
import Layout from '../components/template/Layout';
import { useNetworkStatus } from 'react-adaptive-hooks/network';

function Test() {
  const { effectiveConnectionType } = useNetworkStatus();
  return (
    <Layout>
      <p>test</p>
    </Layout>
  );
}

export default Test;
```

**Comment by frontcraft** [comment]
I got the same error when i minify the code on build with babel-minify-webpack-plugin or uglifyjs-webpack-plugin.  The error is not so verbal:

```
ERROR in unknown: Unexpected token (197:11)
ERROR in unknown: Unexpected token (197:11)
ERROR in unknown: Unexpected token (63:11)
ERROR in unknown: Unexpected token (63:11)
```

**Comment by anton-karlovskiy** [comment]
@eltonjothi @frontcraft 
This is one demo project using `react-adaptive-hooks` package bootstrapped with create-next-app.
Could you please check [this webpack configuration](https://github.com/GoogleChromeLabs/adaptive-loading/blob/b0d03fdcd26088d992a60602ce04d94b7a0418e5/next-show-adaptive-loading/next.config.js#L35)?
I think as ESM build is not working server side we need to transpile or use UMD build.

https://github.com/GoogleChromeLabs/adaptive-loading/tree/master/next-show-adaptive-loading
https://adaptive-loading.web.app/next-show-adaptive-loading/

**Comment by addyosmani** [comment]
Hey folks. As Anton noted earlier, there was a known issue here when using the hooks in a web framework that also involves server-rendering like Next.js. After speaking with the Next team, our guidance in https://github.com/GoogleChromeLabs/react-adaptive-hooks#server-side-rendering-support is accurate and recommended. We're hopeful we can avoid an extra step here in the future.
