### ISSUE TITLE
[bug] navigator.mediaCapabilities.decodingInfo returns a promise but is treated as a synchronous method in useMediaCapabilities

### ISSUE THREAD

**Issue by anton-karlovskiy** [GoogleChromeLabs/react-adaptive-hooks#50]
@wingleung cc @addyosmani 

```
const useMediaCapabilities = (mediaConfig, initialMediaCapabilities = {}) => {
  let mediaCapabilities = {
    supported,
    hasMediaConfig: !!mediaConfig
  };

  mediaCapabilities = (mediaCapabilities.supported && mediaCapabilities.hasMediaConfig)
    ? navigator.mediaCapabilities.decodingInfo(mediaConfig)
    : {
      ...mediaCapabilities,
      ...initialMediaCapabilities
    };

  return {mediaCapabilities};
};
```

I think `navigator.mediaCapabilities.decodingInfo(mediaConfig)` was considered synchronous method in above implementation but according to [MediaCapabilities.decodingInfo() MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities/decodingInfo), it's asynchronous method that returns a promise.

So I wonder if this hook returns false for `supported` property all the time.
And this highlights an issue with the tests which should be catching such problems.

@wingleung Would you mind addressing this issue? Thank you.

**Comment by anton-karlovskiy** [comment]
@wingleung 

I thought this [dropped battery hook](https://github.com/GoogleChromeLabs/react-adaptive-hooks/commit/e9409b1d85bc2ef81878c46c2ddc3c7c82e281a1) could be helpful for writing tests for async methods.

**Comment by wingleung** [comment]
hmm I guess I was too focused on the test case in the unit tests, PR ready for review ☝️

**Comment by anton-karlovskiy** [comment]
@wingleung cc @addyosmani 

Thank you! I'll review soon.
